# name: Build app and deploy to tencent
# on:
#   #监听push操作
#   push:
#     branches:
#       # master分支，你也可以改成其他分支
#       - master
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     environment: production
#     steps:
#     - name: Deploy to Server
#       uses: easingthemes/ssh-deploy@v4.1.8
#       env:
#           SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
#           ARGS: '-rltgoDzvOn --delete'
#           REMOTE_HOST: '101.43.108.86'
#           REMOTE_USER: root
#           EXCLUDE: /*
#           SCRIPT_AFTER: |
#             cd /var/projects/html-project/
#             git pull origin master
